### PR TITLE
Adding support for validating nested objects.

### PR DESCRIPTION
**Pull request by tomasmck**

### CODE REVIEW

**Comment by jameslnewell** [comment]
@ramesius

**Comment by ramesius** [comment]
~~Having a look now, got a question.~~

~~Is it possible to have both filters and children for a single property.~~

~~https://github.com/tomasmck/schema-validator/blob/feature/nestedValidation/lib/index.js#L57~~

~~Looks like if you have filters for a property, then child properties will not get evaluated.~~

Edit: As discussed in slack, filters don't need to be ran on objects at this stage.
Aswell as this, just more test coverage for a 'happy path'.
@jameslnewell Do you have anything else to add?

**Comment by tomasmck** [comment]
@jameslnewell @ramesius do I need to bump the version?

**Comment by ramesius** [comment]
We will bump the version once this is merged in

**Comment by jameslnewell** [comment]
Thanks @tomasmck !

**Pull request merged**
